# Generated by Django 2.1.7 on 2019-03-08 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_created_date', models.DateTimeField(auto_now_add=True)),
                ('note_last_modified_date', models.DateTimeField()),
                ('note_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('note_title', models.CharField(max_length=255)),
                ('note_text', models.TextField()),
                ('note_image_src', models.URLField(blank=True, default=None, null=True)),
                ('note_archived', models.BooleanField(default=False)),
                ('note_pinned', models.BooleanField(default=False)),
                ('note_color', models.CharField(default='#FFF', max_length=20)),
                ('note_reminder', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoteReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.PositiveIntegerField(choices=[(0, 'Email'), (1, 'SMS'), (2, 'Radio'), (3, 'Laser')])),
                ('reminder_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reminder_text', models.TextField()),
                ('reminder_notification_delta', models.PositiveIntegerField(default=30)),
                ('reminder_notification_delta_type', models.CharField(default='minutes', max_length=50)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_date', models.DateTimeField()),
                ('reminder_status', models.PositiveIntegerField(choices=[(0, 'Created'), (1, 'Pending'), (2, 'Queued'), (4, 'Sent'), (5, 'Bounced')])),
            ],
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='note_reminders',
            field=models.ManyToManyField(to='notes.NoteReminder'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_tags',
            field=models.ManyToManyField(to='notes.NoteTag'),
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
