# Generated by Django 2.1.7 on 2019-03-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_reminders',
        ),
        migrations.AddField(
            model_name='note',
            name='note_reminders',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='notes.NoteReminder'),
        ),
    ]
